### ISSUE TITLE
docker 0.2.6 version cannot run

### ISSUE THREAD

**Issue by aaro-n** [ankicommunity/anki-sync-server-rs#57]
# Problem Description
Try to use docker compose to run version 0.2.6. When running, it prompts `anki-container | /usr/local/bin/ankisyncd: error while loading shared libraries: libssl.so.3: cannot open shared object file: No such file or directory`,The previous version was fine.
# Docker Compose
```
version: "3"

services:
    anki-container:
        image: ankicommunity/anki-sync-server-rs:latest
        container_name: anki-container
        restart: unless-stopped
        environment:
          - ANKISYNCD_USERNAME=test
          - ANKISYNCD_PASSWORD=123456
        ports:
          - "27701:27701"
```
